### PR TITLE
Tania2

### PR DESCRIPTION
**Pull request by TaniaY21**
I added a few things:

1) Categories are filtered so the ones we marked  in the google docs are no longer included in the quiz via `function cleanCategory(category)`

2) If category 29 (comics) is picked the boolean game mode is disabled. We could do this for other categories that have a good number of **multiple questions** but very few booleans. 

3) If the game mode selected is true/false, the difficulty dropdown gets disabled. This way the url requested doesnt provide a "difficulty" parameter so all boolean questions are combined to create 10 or more questions.

### CODE REVIEW

**Review by Claryyy — APPROVED** [review]
Looks good to me, well done Tania!

**Review by Toby-D-Smith — APPROVED** [review]
Looks good, have you got rid of the random quiz button?

**Comment by TaniaY21** [comment]
> Looks good, have you got rid of the random quiz button?

No I havent why? :o

**Comment by Toby-D-Smith** [comment]
> 
> 
> > Looks good, have you got rid of the random quiz button?
> 
> No I havent why? :o



> 
> 
> > Looks good, have you got rid of the random quiz button?
> 
> No I havent why? :o

In the main.js it looks like you've removed a lot of the code needed for it

**Pull request merged**
